title: "Malicious URL Detection using Machine Learning"
description: "We developed a machine learning model to detect malicious URLs by combining lexical, host-based, and content-based features, overcoming the limitations of traditional blacklisting methods.
Using the Random Forest algorithm, our approach analyzes specific URL attributes such as length, HTTP tokens, domain age, Google index status, web traffic, and the presence of iframe or right-click events. Trained on a dataset of 11,000 URLs from the UCI Machine Learning Repository, the model achieved 94.7% accuracy."
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false
show_title: false
google_analytics: UA-XXXXXXXX-X
